[build-system]
requires = ["setuptools>=45"]
build-backend = "setuptools.build_meta"

[project]
name = "chewdoc"
version = "0.1.0"
description = "Makes docs that both AI and humans can easily understand and work with"
authors = [{name = "Roma Romanov", email = "puroman@gmail.com"}]
readme = "README.md"
requires-python = ">=3.8.1"
dependencies = [
    "click>=8.1.0",  # CLI interface and command handling
    "requests>=2.25.1",  # HTTP requests for PyPI API interactions
    "tomli>=0.10.2",  # TOML parsing for pyproject.toml files
    "rich>=10.0.0"  # Enhanced terminal output and formatting
]

[project.optional-dependencies]
dev = [
    "pytest >=7.0",  # Testing framework
    "pytest-cov >=4.0",  # Test coverage reporting
    "flake8 >=6.0",  # Linting and code style checking
    "black >=23.0"  # Code formatting
]

# Configures setuptools to automatically find and include all Python packages
# that start with "chewdoc" when building the distribution

[tool.setuptools.packages.find]
where = ["src"]
include = ["chewdoc*"]